language: android

env:
  global:
    - GRADLE_VERSION=4.4
    - ANDROID_API_LEVEL=27
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
  matrix:
    - API=android-19 ABI=armeabi-v7a
    - API=android-21 ABI=armeabi-v7a
    - API=android-22 ABI=armeabi-v7a
    - API=android-24 ABI=armeabi-v7a
    - API=android-24 ABI=arm64-v8a

android:
  components:
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-${ANDROID_BUILD_TOOLS_VERSION}
    # The SDK version used to compile your project
    - android-${ANDROID_API_LEVEL}

before_install:
    # Setup the correct gradle version.
    - wget http://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
    - unzip gradle-${GRADLE_VERSION}-bin.zip
    - export GRADLE_HOME=$PWD/gradle-${GRADLE_VERSION}
    - export PATH=$GRADLE_HOME/bin:$PATH

before_script:
  - android-update-sdk --components=sys-img-$ABI-$API --accept-licenses='android-sdk-license-[0-9a-f]{8}'
  - echo no | android create avd --force -n test -t $API --abi $ABI
  - emulator -avd test -no-audio -no-window
  - android-wait-for-emulator
  - adb shell input keyevent 82 &